### ISSUE TITLE
Some questions about assignment.

### ISSUE THREAD

**Issue by invpr0j** [soulve-innovations/assignment-backend-hospital-product-catalog#1]
Hi @yelizyengi,
If it's possible, I want to ask you some questions about technical assignment.

1) To begin with, I've got a question about project structure and repository. 
Is it a requirement to put application - in "src" directory and tests in "tests", or i can use my own project structure?

2) Is it ok if application functionality is not fully covered by unit tests ?
I made my application fully testable (w Unit/Integration tests), but to cover all of the functionality and all of the possible cases 
(to write all possible tests, positive/negative cases, refactor them), it will take a lot of time.

3) According to the task requirements - "Clear and to the point readme on usage;"
Is it ok to fully rewrite README.md or do I need to create another text file with app description ?
And also I would like to ask about the contents of the readme file. If I'm correct, I should specify steps for build and deployment process, and also provide some kind of API Specification. So, am I getting this requirement right ? 

Thank you in advance for the answers and your time.
Best regards,
Vladyslav Nauholniy.

**Comment by yelizyengi** [comment]
Hello Vladyslav,

1. You can create your own project structure, how you feel more comfortable.
2. You don't need to cover all functional tests.
3. You can use the existing readme file.

Best Regards
Yeliz Yengi



invpr0j ***@***.***>, 4 Nis 2022 Pzt, 10:26 tarihinde şunu
yazdı:

**Comment by invpr0j** [comment]
Thank you very much for the answer. Task will be completed soon. 

Best regards,
Vladyslav Nauholniy
